### ISSUE TITLE
play button gives error on Safari and Chrome ( OS X 10.8.5 ) 

### ISSUE THREAD

**Issue by ofTheo** [olab-io/ofSketch#51] opened 2014-06-10 20:23 UTC
the IDE shows up in the browser great - both on Safari and Chrome.
But the play button just results in this. 

![screen shot 2014-06-10 at 4 22 08 pm](https://cloud.githubusercontent.com/assets/144000/3236352/111d0a14-f0dd-11e3-9059-69547613c19e.png)

this is the case with both Safari and Chrome.

**Comment by brannondorsey** [comment] 2014-06-10 20:28
Did you download the [.zip release](https://github.com/olab-io/ofSketch/releases) or fork the project? If you forked, there must be an openFrameworks >= v0.8.1 distro in the `data/` folder (named openFrameworks) in order for any projects to run.

**Comment by brannondorsey** [comment] 2014-06-10 20:32
Are there any notable Javascript console messages or server logs (press the grid-like button on the toolbar)?

**Comment by ofTheo** [comment] 2014-06-10 20:38
Hi @brannondorsey I downloaded the zip release from: https://github.com/olab-io/ofSketch/releases/ 
the server logs don't produce any errors ( see attached image ) 

I don't see any JS console messages either. 

![screen shot 2014-06-10 at 4 35 40 pm](https://cloud.githubusercontent.com/assets/144000/3236531/e4c123c2-f0de-11e3-897c-d96a70008c2d.png)

**Comment by brannondorsey** [comment] 2014-06-10 20:56
Very strange. Does anything ever pop up on the ofSketch emulated console below the editor?

**Comment by ofTheo** [comment] 2014-06-10 21:26
no nothing - it stays completely blank. 

I am on OS X 10.8.5 
Safari 6.1.4 with WebGL enabled 
Chrome 35.0.1916.153

 Thanks!!

**Comment by bakercp** [comment] 2014-06-16 03:09
Just to confirm, I get this error on a 10.7.5 machine.  So, perhaps it has something to do with machines running 10.7/10.8?

**Comment by bakercp** [comment] 2014-07-16 19:12
I still haven't had a chance to test this on an older machine -- there's a chance it was fixed with the 0.2.0 release -- @ofTheo would you mind giving the new version a quick test?  Thanks for your help!

**Comment by brannondorsey** [comment] 2014-07-26 23:09
Just tried on 10.6.8 and the client immediately disconnects from the server before the ACE Editor can even render.

**Comment by bakercp** [comment] 2014-07-27 00:21
This sounds familiar.  I'm assuming the browser supported web sockets?

**Comment by bakercp** [comment] 2014-07-28 03:40
@brannondorsey we need to confirm that this isn't the same issue that was causing problems with the raspberry pi.  It may be an `ofSystem` issue.  Was the server running on 10.6.8?  Or just the browser?

**Comment by bakercp** [comment] 2014-07-28 03:42
@brannondorsey Also, there must be a 10.8 desktop machine in ATS.  Let's track one down ASAP and test this.  There may be one in my office.

**Comment by brannondorsey** [comment] 2014-07-28 19:59
The server was running on OSX 10.6.8. Seems to be a system thing because I just ran the browser client from the 10.6.8 machine while running the server on my 10.9 machine and everything worked fine.

I also managed to replicate this issue's original bug on the 10.6.8 machine running Google Chrome (Safari (v5.1.7) still can't load the ACE Editor, although I have confirmed that it does support websockets). The only error reported to the front-end is:

```
Unknown Task Queue method.
```

coming from [`ofSketch.js:250`](https://github.com/olab-io/ofSketch/blob/de90c0d9cfa3bf95a63cd4b6f65cdf9e312c3bbf/ofSketchApp/bin/data/DocumentRoot/js/ofSketch/ofSketch.js#L250).

**Comment by bakercp** [comment] 2014-07-28 20:15
Interesting.  I think if we both get in the same room this week, we can figure this out pretty quickly.

I'm not convinced that we need to support OS < 10.7, but it's a good test case to help find extra bugs :)  Can you bring your 10.6 machine to the olab next time you're in?

**Comment by brannondorsey** [comment] 2014-08-01 19:12
@ofTheo, I am having trouble replicating this error on an OSX 10.8 machine. I tried with ofSketch v0.1.1, and the newest v0.2.2 releases. Any chance you could check if you still get this error with the [latest release](https://github.com/olab-io/ofSketch/releases)?

**Comment by bakercp** [comment] 2014-08-04 20:02
Hey all - @ofTheo  if you are still having this error, please reopen the issue -- for now I'll close it in preparation for the 0.3.0 release.

**Closed as completed by bakercp** 2014-08-04 20:02 UTC
Labels: bug, critical

**Comment by ofTheo** [comment] 2014-08-04 22:42
sorry for being slow on this. 
my machine died and I just got a new one, with 10.9 so can’t replicate the issue anymore.

**Comment by brannondorsey** [comment] 2014-08-04 23:06
No worries, and my condolences about the machine. We will leave this closed unless someone else experiences the problem. Thanks!
