### ISSUE TITLE
Segmentation fault when running programs on mac osx

### ISSUE THREAD

**Issue by osiloke** [olab-io/ofSketch#88] opened 2014-08-05 07:05 UTC
A segmentation fault occurs whenever you try to run a program on mac osx. It seems to only seg fault when i compile from the command line (i.e what ofSketch does).

**Comment by bakercp** [comment] 2014-08-05 12:51
Hi @osiloke thanks for the report, though we'll need a bit more information:
- What version of ofSketch?
- What version of OSX?
- What browser are you using?
- What exactly is crashing?  ofSketch itself or the programs produced by ofSketch?
- Please provide a minimal example to reproduce the bug.

**Comment by bakercp** [comment] 2014-08-08 05:33
I'm going to close this.  Please reopen with steps to reproduce.

**Closed as completed by bakercp** 2014-08-08 05:33 UTC

**Comment by osiloke** [comment] 2014-10-02 21:28
Hi, sorry for not getting back to this issue. I had since dropped ofSketch but let me answer your questions.

What version of ofSketch?
0.3.0
What version of OSX?
10.7.5
What browser are you using?
safari
What exactly is crashing? ofSketch itself or the programs produced by ofSketch?
programs produced by ofSketch
Please provide a minimal example to reproduce the bug.
a bare project thats being compiled, basically the compiled program segfaults. 

More info
gcc -v gives

```
gcc -v
Using built-in specs.
Target: i686-apple-darwin11
Configured with: /private/var/tmp/llvmgcc42/llvmgcc42-2336.11~182/src/configure --disable-checking --enable-werror --prefix=/Applications/Xcode.app/Contents/Developer/usr/llvm-gcc-4.2 --mandir=/share/man --enable-languages=c,objc,c++,obj-c++ --program-prefix=llvm- --program-transform-name=/^[cg][^.-]*$/s/$/-4.2/ --with-slibdir=/usr/lib --build=i686-apple-darwin11 --enable-llvm=/private/var/tmp/llvmgcc42/llvmgcc42-2336.11~182/dst-llvmCore/Developer/usr/local --program-prefix=i686-apple-darwin11- --host=x86_64-apple-darwin11 --target=i686-apple-darwin11 --with-gxx-include-dir=/usr/include/c++/4.2.1
Thread model: posix
gcc version 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)
```

I tried 0.4.0, but that just raises 

```
error: unrecognized command line option "-stdlib=libstdc++"
```

More headaches for me because upgrading xcode is not an option for me right now :)
Please kindly take a look at the info.

**Comment by bakercp** [comment] 2014-10-02 22:22
Ahh yes.  This is because of 10.7.  Currently 10.7 is not supported because the openFrameworks makefiles don't support it.  We're working on it though. https://github.com/olab-io/ofSketch/issues/110

**Comment by osiloke** [comment] 2014-10-02 22:55
Ha understood, i'll take a look at that issue
Thanks
